blank_issues_enabled: false
contact_links:
  - name: 项目群聊
    url: https://openai.justsong.cn/
    about: QQ 群：828520184，自动审核，备注 One API
  - name: 赞赏支持
    url: https://iamazing.cn/page/reward
    about: 请作者喝杯咖啡，以激励作者持续开发
